<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CurrenciesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('currencies')->delete();
        $currencies = [
            ['name' => 'Dollars', 'code' => 'USD', 'symbole'=>'$'],
            ['name' => 'Afghanis', 'code' => 'AFN', 'symbole'=>'؋'],
            ['name' => 'Pesos', 'code' => 'ARS', 'symbole'=>'$'],
            ['name' => 'Guilders', 'code' => 'AWG', 'symbole'=>'ƒ'],
            ['name' => 'Dollars', 'code' => 'AUD', 'symbole'=>'$'],
            ['name' => 'New Manats', 'code' => 'AZN', 'symbole'=>'ман'],
            ['name' => 'Dollars', 'code' => 'BSD', 'symbole'=>'$'],
            ['name' => 'Dollars', 'code' => 'BBD', 'symbole'=>'$'],
            ['name' => 'Rubles', 'code' => 'BYR', 'symbole'=>'p.'],
            ['name' => 'Euro', 'code' => 'EUR', 'symbole'=>'€'],
            ['name' => 'Dollars', 'code' => 'BZD', 'symbole'=>'BZ$'],
            ['name' => 'Dollars', 'code' => 'BMD', 'symbole'=>'$'],
            ['name' => 'Bolivianos', 'code' => 'BOB', 'symbole'=>'$b'],
            ['name' => 'Convertible Marka', 'code' => 'BAM', 'symbole'=>'KM'],
            ['name' => 'Pula', 'code' => 'BWP', 'symbole'=>'P'],
            ['name' => 'Leva', 'code' => 'BGN', 'symbole'=>'лв'],
            ['name' => 'Reais', 'code' => 'BRL', 'symbole'=>'R$'],
            ['name' => 'Pounds', 'code' => 'GBP', 'symbole'=>'£'],
            ['name' => 'Dollars', 'code' => 'BND', 'symbole'=>'$'],
            ['name' => 'Riels', 'code' => 'KHR', 'symbole'=>'៛'],
            ['name' => 'Dollars', 'code' => 'CAD', 'symbole'=>'$'],
            ['name' => 'Dollars', 'code' => 'KYD', 'symbole'=>'$'],
            ['name' => 'Pesos', 'code' => 'CLP', 'symbole'=>'$'],
            ['name' => 'Yuan Renminbi', 'code' => 'CNY', 'symbole'=>'¥'],
            ['name' => 'Pesos', 'code' => 'COP', 'symbole'=>'$'],
            ['name' => 'Colón', 'code' => 'CRC', 'symbole'=>'₡'],
            ['name' => 'Kuna', 'code' => 'HRK', 'symbole'=>'kn'],
            ['name' => 'Pesos', 'code' => 'CUP', 'symbole'=>'₱'],
            ['name' => 'Koruny', 'code' => 'CZK', 'symbole'=>'Kč'],
            ['name' => 'Kroner', 'code' => 'DKK', 'symbole'=>'kr'],
            ['name' => 'Pesos', 'code' => 'DOP ', 'symbole'=>'RD$'],
            ['name' => 'Dollars', 'code' => 'XCD', 'symbole'=>'$'],
            ['name' => 'Pounds', 'code' => 'EGP', 'symbole'=>'£'],
            ['name' => 'Colones', 'code' => 'SVC', 'symbole'=>'$'],
            ['name' => 'Pounds', 'code' => 'FKP', 'symbole'=>'£'],
            ['name' => 'Dollars', 'code' => 'FJD', 'symbole'=>'$'],
            ['name' => 'Cedis', 'code' => 'GHC', 'symbole'=>'¢'],
            ['name' => 'Pounds', 'code' => 'GIP', 'symbole'=>'£'],
            ['name' => 'Quetzales', 'code' => 'GTQ', 'symbole'=>'Q'],
            ['name' => 'Pounds', 'code' => 'GGP', 'symbole'=>'£'],
            ['name' => 'Dollars', 'code' => 'GYD', 'symbole'=>'$'],
            ['name' => 'Lempiras', 'code' => 'HNL', 'symbole'=>'L'],
            ['name' => 'Dollars', 'code' => 'HKD', 'symbole'=>'$'],
            ['name' => 'Forint', 'code' => 'HUF', 'symbole'=>'Ft'],
            ['name' => 'Kronur', 'code' => 'ISK', 'symbole'=>'kr'],
            ['name' => 'Rupees', 'code' => 'INR', 'symbole'=>'Rp'],
            ['name' => 'Rupiahs', 'code' => 'IDR', 'symbole'=>'Rp'],
            ['name' => 'Rials', 'code' =>  'IRR', 'symbole'=>'﷼' ],
            ['name' => 'Pounds', 'code' => 'IMP', 'symbole'=>'£'],
            ['name' => 'New Shekels', 'code' => 'ILS', 'symbole'=>'₪'],
            ['name' => 'Dollars', 'code' => 'JMD', 'symbole'=>'J$'],
            ['name' => 'Yen', 'code' => 'JPY', 'symbole'=>'¥'],
            ['name' => 'Pounds', 'code' => 'JEP', 'symbole'=>'£'],
            ['name' => 'Tenge', 'code' => 'KZT', 'symbole'=>'лв'],
            ['name' => 'Won', 'code' => 'KPW', 'symbole'=>'₩'],
            ['name' => 'Won', 'code' => 'KRW', 'symbole'=>'₩'],
            ['name' => 'Soms', 'code' => 'KGS', 'symbole'=>'лв'],
            ['name' => 'Kips', 'code' => 'LAK', 'symbole'=>'₭'],
            ['name' => 'Lati', 'code' => 'LVL', 'symbole'=>'Ls'],
            ['name' => 'Pounds', 'code' => 'LBP', 'symbole'=>'£'],
            ['name' => 'Dollars', 'code' => 'LRD', 'symbole'=>'$'],
            ['name' => 'Switzerland Francs', 'code' => 'CHF', 'symbole'=>'CHF'],
            ['name' => 'Litai', 'code' => 'LTL', 'symbole'=>'Lt'],
            ['name' => 'Denars', 'code' => 'MKD', 'symbole'=>'ден'],
            ['name' => 'Ringgits', 'code' => 'MYR', 'symbole'=>'RM'],
            ['name' => 'Rupees', 'code' => 'MUR', 'symbole'=>'₨'],
            ['name' => 'Pesos', 'code' => 'MXN', 'symbole'=>'$'],
            ['name' => 'Tugriks', 'code' => 'MNT', 'symbole'=>'₮'],
            ['name' => 'Meticais', 'code' => 'MZN', 'symbole'=>'MT'],
            ['name' => 'Dollars', 'code' => 'NAD', 'symbole'=>'$'],
            ['name' => 'Rupees', 'code' => 'NPR', 'symbole'=>'₨'],
            ['name' => 'Guilders', 'code' => 'ANG', 'symbole'=>'ƒ'],
            ['name' => 'Dollars', 'code' => 'NZD', 'symbole'=>'$'],
            ['name' => 'Cordobas', 'code' => 'NIO', 'symbole'=>'C$'],
            ['name' => 'Nairas', 'code' => 'NGN', 'symbole'=>'₦'],
            ['name' => 'Krone', 'code' => 'NOK', 'symbole'=>'kr'],
            ['name' => 'Rials', 'code' => 'OMR', 'symbole'=> '﷼' ],
            ['name' => 'Rupees', 'code' => 'PKR', 'symbole'=>'₨'],
            ['name' => 'Balboa', 'code' => 'PAB', 'symbole'=>'B/.'],
            ['name' => 'Guarani', 'code' => 'PYG', 'symbole'=>'Gs'],
            ['name' => 'Nuevos Soles', 'code' => 'PEN', 'symbole'=>'S/.'],
            ['name' => 'Pesos', 'code' => 'PHP', 'symbole'=>'Php'],
            ['name' => 'Zlotych', 'code' => 'PLN', 'symbole'=>'zł'],
            ['name' => 'Rials', 'code' => 'QAR', 'symbole'=>'﷼'],
            ['name' => 'New Lei', 'code' => 'RON', 'symbole'=>'lei'],
            ['name' => 'Rubles', 'code' => 'RUB', 'symbole'=>'руб'],
            ['name' => 'Pounds', 'code' => 'SHP', 'symbole'=>'£'],
            ['name' => 'Riyals', 'code' =>  'SAR', 'symbole'=>'﷼'],
            ['name' => 'Dinars', 'code' => 'RSD', 'symbole'=>'Дин.'],
            ['name' => 'Rupees', 'code' => 'SCR', 'symbole'=>'₨'],
            ['name' => 'Dollars', 'code' => 'SGD', 'symbole'=>'$'],
            ['name' => 'Dollars', 'code' => 'SBD', 'symbole'=>'$'],
            ['name' => 'Shillings', 'code' => 'SOS', 'symbole'=>'S'],
            ['name' => 'Rand', 'code' => 'ZAR', 'symbole'=>'R'],
            ['name' => 'Rupees', 'code' => 'LKR', 'symbole'=>'₨'],
            ['name' => 'Kronor', 'code' => 'SEK', 'symbole'=>'kr'],
            ['name' => 'Dollars', 'code' => 'SRD', 'symbole'=>'$'],
            ['name' => 'Pounds', 'code' => 'SYP', 'symbole'=>'£'],
            ['name' => 'New Dollars', 'code' => 'TWD', 'symbole'=>'NT$'],
            ['name' => 'Baht', 'code' => 'THB', 'symbole'=>'฿'],
            ['name' => 'Dollars', 'code' => 'TTD', 'symbole'=>'TT$'],
            ['name' => 'Lira', 'code' => 'TRY', 'symbole'=>'TL'],
            ['name' => 'Liras', 'code' => 'TRL', 'symbole'=>'£'],
            ['name' => 'Dollars', 'code' => 'TVD', 'symbole'=>'$'],
            ['name' => 'Hryvnia', 'code' => 'UAH', 'symbole'=>'₴'],
            ['name' => 'Pesos', 'code' => 'UYU', 'symbole'=>'$U'],
            ['name' => 'Sums', 'code' => 'UZS', 'symbole'=>'лв'],
            ['name' => 'Bolivares Fuertes', 'code' => 'VEF', 'symbole'=>'Bs'],
            ['name' => 'Dong', 'code' => 'VND', 'symbole'=>'₫'],
            ['name' => 'Rials', 'code' =>  'YER', 'symbole'=>'﷼' ],
            ['name' => 'Zimbabwe Dollars', 'code' => 'ZWD', 'symbole'=>'Z$'],
        ];
        DB::table('currencies')->insert($currencies);
    }
}
